/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BulkMemberInput {
  'membershipNumber' : string,
  'receipt2022' : [] | [string],
  'receipt2023' : [] | [string],
  'receipt2024' : [] | [string],
  'receipt2025' : [] | [string],
  'receipt2026' : [] | [string],
  'receipt2027' : [] | [string],
  'receipt2028' : [] | [string],
  'receipt2029' : [] | [string],
  'receipt2030' : [] | [string],
  'receiptPriorTo2021' : [] | [string],
  'area' : string,
  'name' : string,
  'mobileNo' : string,
  'alternateMobile' : [] | [string],
  'priorTo2021' : [] | [boolean],
  'address' : string,
  'familyMemberCount' : [] | [bigint],
  'spouseName' : string,
  'year2022' : [] | [boolean],
  'year2023' : [] | [boolean],
  'year2024' : [] | [boolean],
  'year2025' : [] | [boolean],
  'year2026' : [] | [boolean],
  'year2027' : [] | [boolean],
  'year2028' : [] | [boolean],
  'year2029' : [] | [boolean],
  'year2030' : [] | [boolean],
}
export interface Member {
  'id' : MemberID,
  'membershipNumber' : string,
  'receipt2022' : [] | [string],
  'receipt2023' : [] | [string],
  'receipt2024' : [] | [string],
  'receipt2025' : [] | [string],
  'receipt2026' : [] | [string],
  'receipt2027' : [] | [string],
  'receipt2028' : [] | [string],
  'receipt2029' : [] | [string],
  'receipt2030' : [] | [string],
  'receiptPriorTo2021' : [] | [string],
  'area' : string,
  'name' : string,
  'mobileNo' : string,
  'alternateMobile' : [] | [string],
  'priorTo2021' : [] | [boolean],
  'address' : string,
  'familyMemberCount' : [] | [bigint],
  'spouseName' : string,
  'year2022' : [] | [boolean],
  'year2023' : [] | [boolean],
  'year2024' : [] | [boolean],
  'year2025' : [] | [boolean],
  'year2026' : [] | [boolean],
  'year2027' : [] | [boolean],
  'year2028' : [] | [boolean],
  'year2029' : [] | [boolean],
  'year2030' : [] | [boolean],
}
export type MemberID = string;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [bigint],
      string,
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [boolean],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
      [] | [string],
    ],
    MemberID
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddMembers' : ActorMethod<[Array<BulkMemberInput>], bigint>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMember' : ActorMethod<[MemberID], Member>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];