/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MemberID = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BulkMemberInput = IDL.Record({
  'membershipNumber' : IDL.Text,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'mobileNo' : IDL.Text,
  'alternateMobile' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'familyMemberCount' : IDL.Opt(IDL.Nat),
  'spouseName' : IDL.Text,
});
export const Member = IDL.Record({
  'id' : MemberID,
  'membershipNumber' : IDL.Text,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'mobileNo' : IDL.Text,
  'alternateMobile' : IDL.Opt(IDL.Text),
  'address' : IDL.Text,
  'familyMemberCount' : IDL.Opt(IDL.Nat),
  'spouseName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Text,
      ],
      [MemberID],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddMembers' : IDL.Func([IDL.Vec(BulkMemberInput)], [IDL.Nat], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMember' : IDL.Func([MemberID], [Member], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MemberID = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BulkMemberInput = IDL.Record({
    'membershipNumber' : IDL.Text,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'mobileNo' : IDL.Text,
    'alternateMobile' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'familyMemberCount' : IDL.Opt(IDL.Nat),
    'spouseName' : IDL.Text,
  });
  const Member = IDL.Record({
    'id' : MemberID,
    'membershipNumber' : IDL.Text,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'mobileNo' : IDL.Text,
    'alternateMobile' : IDL.Opt(IDL.Text),
    'address' : IDL.Text,
    'familyMemberCount' : IDL.Opt(IDL.Nat),
    'spouseName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Text,
        ],
        [MemberID],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddMembers' : IDL.Func([IDL.Vec(BulkMemberInput)], [IDL.Nat], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMember' : IDL.Func([MemberID], [Member], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };